markdown: redcarpet
redcarpet:
  extensions: [ "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data" ]

title: Gistnote
url: https://gistnote.github.io
github:
  url: https://github.com/gistnote/gistnote.github.io
  owner: gistnote
  repo: gistnote.github.io
